# Generated by Django 5.0.2 on 2024-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_reportero_options_alter_reportero_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportero',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
