# Generated by Django 5.0.2 on 2024-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_rename_acta_nacimineto_reportero_acta_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('reportero', models.IntegerField()),
            ],
        ),
    ]
